In [248]:
import math
import pandas as pd
import numpy as np

In [9]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >=6:
    print("Hello, World")
    print(f"Python version: {sys.version}")
else:
    print("Please use python 3.6 or higher")

Hello, World
Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]


In [10]:
my_list= [1,2,3]
print("Original List:", my_list)
my_list.append(4)
print("Modified List:", my_list)

my_tuple=(1,2,3)
print("My tuple: ", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
My tuple:  (1, 2, 3)


In [11]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [12]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [13]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [14]:
colors = ("red","green", "yellow", "blue")
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = "purple"

colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


TypeError: 'tuple' object does not support item assignment

In [22]:
person = {"name":"John","age":30,"city":"Pittsburgh"}
print(f"Hello my name is {person["name"]}. I am {person["age"]} years old and I live at {person["city"]}")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [24]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [26]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [28]:
# Define two boolean variables
a = True
b = False
# Using the "and" operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False") # This will be printed
# Using the "or" operator
if a or b:
    print("At least one of a or b is True") # This will be printed
else:
    print("Both a and b are False")
# Using the "not" operator
if not a:
    print("a is False") # This will not be printed
else:
    print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


In [30]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
    print(fruit)
# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break
# Continiue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


In [40]:
def add_binary(a, b):
    '''
    Returns the sum of two decimal numbers in binary digits.
    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer
    Returns:
    binary_sum (str): Binary string of the sum of a and b
    '''
    binary_sum = bin(a+b)[2:]
    return binary_sum

In [42]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class "int">
total = sum([1, 2, 3]) # Output: 6

Hello, World!


In [46]:
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25
print(age)

25


In [52]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.
    This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
    Fahrenheit to Celsius)
    and then asks for the temperature value. It calculates and returns the converted temperature.
    Returns:
    float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")
    if choice == "1":
    # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit
    elif choice == "2":
    # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius
    else:
        print("Invalid choice. Please enter 1 or 2.")
    return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius


Enter 1 or 2:  2
Enter temperature in Fahrenheit:  100


100.0F is equal to 37.77777777777778C


37.77777777777778

In [56]:
x = 10 # Global Variable.
def print_global():
    print(x) # Accessing global variable
print_global() # Output: 10

10


In [58]:
def print_local():
    y = 5 # Local variable
    print(y)
print_local() # Output: 5
print(y) # T

5


NameError: name 'y' is not defined

In [66]:
x = 10 # Global variable
def modify_global():
    global x # Declaring x as global
    x = 20 # Modifying global x
modify_global()
print(x) # Output: 20

20


# Exercises

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types

In [85]:
def convert_unit(value, entry, output,  dictionary):
    if entry not in dictionary or output not in dictionary:
        return "Error/;  Invalid units"

    base_value = value * dictionary[entry]
    result = base_value / dictionary[output]
    return result

def main():
    try:
        convert = input("Choose conversion type length, weight , or volume: type(l,w,v):  ").lower()

        length = {'meter':1,'kilometer':1000, 'centimeter':0.01}
        weight = {'kilograms':1,'gram':0.001,'pound':0.4535}
        volume = {'liter':1,'mililiter':0.001,'gallon':3.7854}


        if convert == 'l':
            unit = length
        elif convert == 'w':
            unit = weight
        elif convert =='v':
            unit = volume
        else:
            print("Error:Invalid conversion type")
            return

        value = float(input("Enter value you want to convert: "))
        entry = input(f"Enter unit to convert from (e.g.,{','.join(unit.keys())}):").lower()
        output = input(f"Enter unit to convert to (e.g.,{','.join(unit.keys())}):").lower()

        result = convert_unit(value,entry,output,unit)

        if isinstance(result,str):
            print(result)
        else:
            print(f"{value}{entry} is equal to {result}{output}")
    except ValueError:
        print("Error: Please enter a valid numeral")
    except Exception as e:
        print(f"An unexpected error occured : {e}")

if __name__=="__main__":
    main()


Choose conversion type length, weight , or volume: type(l,w,v):   l
Enter value you want to convert:  50
Enter unit to convert from (e.g.,meter,kilometer,centimeter): centimeter
Enter unit to convert to (e.g.,meter,kilometer,centimeter): meter


50.0centimeter is equal to 0.5meter


Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [109]:
def calc_sum(numbers):
    '''
    Calculate sum from list of numbers. Parameter here is a list 
    return a float sum of numbers
    '''
    return sum(numbers)

def calc_avg(numbers):
    '''
    Calculate average from list of numbers. Parameter here is a list 
    return a float average of numbers
    '''
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of an empty list")
    return sum(numbers) / len(numbers)

def calc_max(numbers):
    '''
    Calculate maximum value from list of numbers. Parameter here is a list 
    return a maximum value among numbers
    '''
    if len(numbers) == 0:
        raise ValueError("Cannot calculate maximum of an empty list")
    return max(numbers)

def calc_min(numbers):
    '''
    Calculate minimum value from list of numbers. Parameter here is a list 
    return a minimum value among numbers
    '''
    if len(numbers) == 0:
        raise ValueError("Cannot calculate minimum of an empty list")
    return min(numbers)

def main():
    try:
        print("Choose any one option:")
        print("1 for sum")
        print("2 for Average")
        print("3 for Maximum")
        print("4 for Minimum")

        operation = int(input("Enter the number correspondance to choices: "))

        input_number = input("Enter a list of numbers separated by spaces: ")

        numbers = [float(num) for num in input_number.split()]

        if len(numbers) == 0:
            print("Error: The list can't be empty")

        if operation == 1:
            result = calc_sum(numbers)
            print("The sum of numbers is:",result)
        elif operation == 2:
            result = calc_avg(numbers)
            print("The average of numbers is:",result)
        elif operation == 3:
            result = calc_max(numbers)
            print("The Maximum of numbers is:",result)
        elif operation == 4:
            result = calc_min(numbers)
            print("The Minimum of numbers is:",result)
        else:
            print("Error: invalid choices")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occures: {e}")

if __name__ == "__main__":
    main()

Choose any one option:
1 for sum
2 for Average
3 for Maximum
4 for Minimum


Enter the number correspondance to choices:  4
Enter a list of numbers separated by spaces:  23 43 54 12.5


The Minimum of numbers is: 12.5


# 4.2 Exercise on List Manipulation:

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [116]:
def extract_every_other(lst):   
    return lst[::2]

def main():
    lst = [1,2,3,4,5,6]
    result = extract_every_other(lst)
    print("After every second elements elimination lst looks like: ", result)

if __name__ == "__main__":
    main()

After every second elements elimination lst looks like:  [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [120]:
def sublist(lst,start,end):        
    return lst[start:end+1]

def main():
    input_number = input("Enter a list of numbers separated by spaces: ")
    lst = [float(num) for num in input_number.split()]
    print("Your list is: ", lst)
    start = int(input("Enter starting point for sub list"))
    end = int(input("Enter ending point for sub list")    )
    result = sublist(lst,start,end)
    print("Your sublist look like ", result)

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces:  34 54 34 12 32 98 07 


Your list is:  [34.0, 54.0, 34.0, 12.0, 32.0, 98.0, 7.0]


Enter starting point for sub list 2
Enter ending point for sub list 5


Your sublist look like  [34.0, 12.0, 32.0, 98.0]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [122]:
def reverse(lst):        
    return lst[::-1]

def main():
    input_number = input("Enter a list of numbers separated by spaces: ")
    lst = [float(num) for num in input_number.split()]
    print("Your list is: ", lst)
    
    result = reverse(lst)
    print("Your reversed list look like ", result)

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces:  32 44 12 97 85


Your list is:  [32.0, 44.0, 12.0, 97.0, 85.0]
Your reversed list look like  [85.0, 97.0, 12.0, 44.0, 32.0]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [132]:
def newlist(lst):        
    return lst[1:-1]

def main():
    input_number = input("Enter a list of numbers separated by spaces: ")
    lst = [float(num) for num in input_number.split()]
    print("Your list is: ", lst)
    result = newlist(lst)
    print("Your sublist look like ", result)

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces:  12 32 44 12 32 33 


Your list is:  [12.0, 32.0, 44.0, 12.0, 32.0, 33.0]
Your sublist look like  [32.0, 44.0, 12.0, 32.0]


Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [136]:
def get_first_n(lst,n):        
    return lst[:n]

def main():
    input_number = input("Enter a list of numbers separated by spaces: ")
    lst = [float(num) for num in input_number.split()]
    print("Your list is: ", lst)
    search = int(input("Enter n elemnts to extract from list"))
    
    result = get_first_n(lst,search)
    print("Your n element from start look like ", result)

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces:  12 32 42 12 34


Your list is:  [12.0, 32.0, 42.0, 12.0, 34.0]


Enter n elemnts to extract from list 2


Your n element from start look like  [12.0, 32.0]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [148]:
def get_last_n(lst,n):        
    return lst[-n:]

def main():
    input_number = input("Enter a list of numbers separated by spaces: ")
    lst = [float(num) for num in input_number.split()]
    print("Your list is: ", lst)
    search = int(input("Enter n elemnts to extract from list"))
    
    result = get_last_n(lst,search)
    print("Your sublist look like ", result)

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces:  12 32 44 13 54


Your list is:  [12.0, 32.0, 44.0, 13.0, 54.0]


Enter n elemnts to extract from list 2


Your sublist look like  [13.0, 54.0]


Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [164]:
def rev(lst,n):        
    return lst[-n::-n]

def main():
    input_number = input("Enter a list of numbers separated by spaces: ")
    lst = [float(num) for num in input_number.split()]
    print("Your list is: ", lst)
    search = int(input("Enter n elemnts to skip from list"))
    
    result = rev(lst,search)
    print("Your new reverse look like ", result)

if __name__ == "__main__":
    main()

Enter a list of numbers separated by spaces:  2 4 12 34 12 34 65 34


Your list is:  [2.0, 4.0, 12.0, 34.0, 12.0, 34.0, 65.0, 34.0]


Enter n elemnts to skip from list 3


Your new reverse look like  [34.0, 12.0]


# 4.3 Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [168]:
def flatten(lst):
    flattened_list = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse into it
            flattened_list.extend(flatten(item))
        else:
            flattened_list.append(item)  # If the item is not a list, add it to the flattened list
    return flattened_list


def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    
    # Convert the string input to an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("Please enter a valid nested list.")
            return
        flattened = flatten(nested_list)
        print("Flattened List:", flattened)
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")


if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[4,3,2],[2,4],1,3,[9,8]]


Flattened List: [4, 3, 2, 2, 4, 1, 3, 9, 8]


Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [182]:
def access_nested_element(lst,indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")

    # Convert the user input (string) into an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("The input is not a valid list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")
        return

    index_input = input("Enter indices value like [1,2]: ")

    # Convert the indices input into a list
    try:
        indices = eval(index_input)
        if not isinstance(indices, list):
            print("The indices must be provided as a list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the indices are in list format.")
        return
    result = access_nested_element(nested_list,indices)
    print(f"You elements for index {indices} is {result}")

if __name__ == "__main__":
    main()
    

Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[1,2,3],[4,5],[6,7,8,9]]
Enter indices value like [1,2]:  [2,3]


You elements for index [2, 3] is 9


Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [192]:
def sum_nested(lst):
    totalsum = 0
    for elements in lst:
        if isinstance(elements,list):
            totalsum += sum_nested(elements)
        else:
            totalsum += elements
    return totalsum

def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")

    # Convert the user input (string) into an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("The input is not a valid list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")
        return

    
    result = sum_nested(nested_list)
    print(f"You sum of element is {result}")

if __name__ == "__main__":
    main()
    

Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[1,2,3],[4,5],[6,7,8,9]]


You sum of element is 45


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [208]:
def remove_element(lst, elem):
    # Initialize a new list to store the result
    new_lst = []
    
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse
            new_lst.append(remove_element(item, elem))  # Recurse on the nested list
        elif item != elem:  # If the item is not the element we want to remove, add it to new_lst
            new_lst.append(item)
    
    return new_lst

def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    element = int(input("Enter the element you want to remove: "))
    
    # Convert the user input (string) into an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("The input is not a valid list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")
        return
    
    # Remove the element
    result = remove_element(nested_list, element)
    
    print(f"The list after removing the element {element} is: {result}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[1,2,3],[4,5],[6,7,2]]
Enter the element you want to remove:  2


The list after removing the element 2 is: [[1, 3], [4, 5], [6, 7]]


Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [221]:
def find_max(lst):
    max_value=0
    for elem in lst:
        if isinstance(elem,list):
            max_value = max(max_value,find_max(elem))
        else:
            max_value = max(max_value,elem)
      
    
    return max_value

def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    
    
    # Convert the user input (string) into an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("The input is not a valid list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")
        return
    
    # Remove the element
    result = find_max(nested_list)
    
    print(f"The maximum element in list is:  {result}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[42,32],[11,65]]


The maximum element in list is:  65


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [229]:
def count_occurrences(lst, elem):
    count = 0
    
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse
            count+=count_occurrences(item, elem)
        else:
            if item == elem:
                count +=1
        
    
    return count

def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    element = int(input("Enter the element you want to count: "))
    
    # Convert the user input (string) into an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("The input is not a valid list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")
        return
    
    # Remove the element
    result = count_occurrences(nested_list, element)
    
    print(f"The count of element {element} is: {result}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[1,2,1,3],[3,1,4,1,5]]
Enter the element you want to count:  1


The count of element 1 is: 4


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].


In [233]:
def flatten(lst):
    flattened_list = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse into it
            flattened_list.extend(flatten(item))
        else:
            flattened_list.append(item)  # If the item is not a list, add it to the flattened list
    return flattened_list


def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    
    # Convert the string input to an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("Please enter a valid nested list.")
            return
        flattened = flatten(nested_list)
        print("Flattened List:", flattened)
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")


if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[[1,2],[3,4]],[[5,6],[6,7]]]


Flattened List: [1, 2, 3, 4, 5, 6, 6, 7]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [245]:
def flatten(lst):
    flattened_list = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse into it
            flattened_list.extend(flatten(item))
        else:
            flattened_list.append(item)  # If the item is not a list, add it to the flattened list
    return flattened_list

def average_nested(lst):
    flattened_list = flatten(lst)
    if len(flattened_list) ==0:
        return 0
    total_sum = sum(flattened_list)
    total_length = len(flattened_list)    
    
    return total_sum/total_length

def main():
    # Input: the user is prompted to enter a nested list
    user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")
    
    
    # Convert the user input (string) into an actual list
    try:
        nested_list = eval(user_input)
        if not isinstance(nested_list, list):
            print("The input is not a valid list!")
            return
    except Exception as e:
        print(f"Error: {e}. Please ensure the input is a valid nested list.")
        return
    
    # Remove the element
    result = average_nested(nested_list)
    
    print(f"The average value pf this list is:  {result}")

if __name__ == "__main__":
    main()


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[1,2],[3,4],[5,6]]


The average value pf this list is:  3.5


# 10 To - Do - NumPy


10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [264]:
array = np.empty((2,2)) #np.zeros((2,2))
array

array([[0., 0.],
       [0., 0.]])

In [268]:
array = np.ones((4,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [270]:
fill_array = np.full((2,2),4)
fill_array

array([[4, 4],
       [4, 4]])

In [282]:
given_array = np.array([[1,2],[3,4]])
print(given_array)

array2 = np.zeros_like(given_array)
print(array2)

[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


In [284]:
array2 = np.ones_like(given_array)
print(array2)

[[1 1]
 [1 1]]


In [286]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [304]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [310]:
array = np.arange(0,9)
matrix = array.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [312]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [314]:
array = np.random.random(30)
print(array)
mean = array.mean()
print(mean)

[0.66761262 0.37385079 0.38666954 0.38929003 0.16583355 0.42829103
 0.44090224 0.37982568 0.93207713 0.26410234 0.16622803 0.67460888
 0.96693786 0.49463007 0.85125074 0.30581798 0.53140734 0.57855525
 0.40033011 0.37905086 0.71185479 0.09466444 0.37048008 0.26275011
 0.76460476 0.85785318 0.93687064 0.28005848 0.66472852 0.66449426]
0.5128543768859489


In [320]:
array = np.random.random((10,10))
min_value = array.min()
print(min_value)
max_value = array.max()
print(max_value)

0.011260584357945747
0.9688595865316599


In [324]:
array= np.zeros(10)
array[4] =1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [336]:
arr = [1,2,0,0,4,0]
rev_arr = arr[::-1] #arr.reverse()
rev_arr


[0, 4, 0, 0, 2, 1]

In [346]:
size = int(input("Enter size of 2d array you want"))

arr = np.ones((size,size),dtype=int)

arr[1:-1,1:-1] = 0

print(arr)
    

Enter size of 2d array you want 5


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [370]:
size = 8

arr = np.ones((size,size),dtype=int)

arr[1::2,::2] = 0
arr[::2,1::2] = 0

print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [374]:
x = np.array([[1,2],[3,5]]) 
y = np.array([[5,6],[7,8]])
v = np.array([9,10]) 
w = np.array([11,12])

In [380]:
z = x+y
u = v+w
print("Z: ",z)
print("U: ",u)

Z:  [[ 6  8]
 [10 13]]
U:  [20 22]


In [382]:
z = x-y
u = v-w
print("Z: ",z)
print("U: ",u)

Z:  [[-4 -4]
 [-4 -3]]
U:  [-2 -2]


In [384]:
z = x *4
u = v*5
a = y*7
b = w*3
print("Z: ",z)
print("U: ",u)
print("A: ",a)
print("B: ",b)

Z:  [[ 4  8]
 [12 20]]
U:  [45 50]
A:  [[35 42]
 [49 56]]
B:  [33 36]


In [388]:
z = np.square(x)
u = np.square(v)
a = np.square(y)
b = np.square(w)
print("Z: ",z)
print("U: ",u)
print("A: ",a)
print("B: ",b)

Z:  [[ 1  4]
 [ 9 25]]
U:  [ 81 100]
A:  [[25 36]
 [49 64]]
B:  [121 144]


In [390]:
z = np.dot(x,y)
u = np.dot(v,w)
a = np.dot(x,v)

print("Z: ",z)
print("U: ",u)
print("A: ",a)


Z:  [[19 22]
 [50 58]]
U:  219
A:  [29 77]


In [404]:
z = np.concatenate((x,y),axis=1)
u = np.stack((v,w),axis=1)


print("Z: ",z)
print("U: ",u)


Z:  [[1 2 5 6]
 [3 5 7 8]]
U:  [[ 9 11]
 [10 12]]


In [410]:
z = np.concatenate((x,v),axis=1)

print("Z: ",z)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

np.concatenates require all arrays to have the same number of dimension when concatenating along axis. but we have 2d and 1d array so they are showing problem. We can solve these by adjusting dimensions like we can use reshape function to convertv from 1d to 2d and it will be available to concatenate

In [413]:
v = v.reshape(-1,1)
z = np.concatenate((x,v),axis=1)

print("Z: ",z)

Z:  [[ 1  2  9]
 [ 3  5 10]]


# Problem - 4: Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

In [415]:
A = np.array([[3,4],[7,8]]) 
B = np.array([[5,3],[2,1]])


In [421]:
# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
identity_matrix = np.dot(A, A_inv)

print("A * A^-1 (should be identity matrix):")
print(identity_matrix)

# Check if the result is an identity matrix
print("\nIs the result the identity matrix?")
print(np.allclose(identity_matrix, np.eye(2)))  # Should return True if it's close to identity matrix


A * A^-1 (should be identity matrix):
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

Is the result the identity matrix?
True


In [431]:
AB= np.dot(A,B)
BA = np.dot(B,A)
print("AB: ")
print(AB)
print("BA: ")
print(BA)

is_equal = np.array_equal(AB,BA)
print("\n Is AB and BA equal?: ")
print(is_equal)
print("Hence Proved AB ̸= BA")

AB: 
[[23 13]
 [51 29]]
BA: 
[[36 44]
 [13 16]]

 Is AB and BA equal?: 
False
Hence Proved AB ̸= BA


In [437]:
AB= np.dot(A,B)
ABt = np.transpose(AB)

At = np.transpose(A)
Bt = np.transpose(B)
BtAt = np.dot(Bt,At)
print("AB transpose: ",ABt)
print("\n A transpose: ",At)
print("\n B transpose: ",Bt)
print("\n BTAT is: ", BtAt)

is_equal = np.array_equal(ABt,BtAt)
print("Is (AB)T and BTAT equal")
print(is_equal)

AB transpose:  [[23 51]
 [13 29]]

 A transpose:  [[3 7]
 [4 8]]

 B transpose:  [[5 2]
 [3 1]]

 BTAT is:  [[23 51]
 [13 29]]
Is (AB)T and BTAT equal
True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [451]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])
B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

X_solve = np.linalg.solve(A, B)
print("Solution for (X,Y,Z): ",X)
print("\n solution for (X,Y,Z0: ",X_solve)

Solution for (X,Y,Z):  [ 2.  1. -2.]

 solution for (X,Y,Z0:  [ 2.  1. -2.]


The np.linalg module in NumPy is specifically designed for linear algebra operations. It provides a collection of functions for solving various types of problems that arise in linear algebra, such as solving systems of linear equations, finding the inverse of a matrix, computing determinants, eigenvalues, and eigenvectors, etc.

Here are the key functions and concepts in np.linalg:
1. np.linalg.inv(A): Matrix Inverse

    Purpose: Computes the inverse of a square matrix AA, if it exists.
    Use case: Often used for solving linear systems or computing transformations.
    Example:

    A_inv = np.linalg.inv(A)

        If AA is a 2x2 matrix, A−1A−1 is its inverse, provided the determinant of AA is non-zero.

2. np.linalg.solve(A, B): Solve Linear Equation

    Purpose: Solves the equation A⋅X=BA⋅X=B for XX, where AA is a square matrix and BB is a vector (or matrix).
    Use case: Directly solves a system of linear equations without computing the inverse manually.
    Example:

    X = np.linalg.solve(A, B)

        This function is numerically more stable than manually computing the inverse and then multiplying by BB.

3. np.linalg.det(A): Determinant of a Matrix

    Purpose: Computes the determinant of a square matrix.
    Use case: The determinant is used to determine if a matrix is invertible (non-zero determinant) or singular (zero determinant).
    Example:

    determinant = np.linalg.det(A)

        A determinant of zero indicates that the matrix is singular and doesn't have an inverse.

4. np.linalg.eig(A): Eigenvalues and Eigenvectors

    Purpose: Computes the eigenvalues and eigenvectors of a square matrix.
    Use case: Used in areas like physics, machine learning (PCA), and statistics.
    Example:

    eigenvalues, eigenvectors = np.linalg.eig(A)

        Eigenvalues give the magnitude of scaling in each principal direction, and eigenvectors represent the directions of these scalings.

5. np.linalg.norm(x): Matrix or Vector Norm

    Purpose: Computes the norm (magnitude) of a vector or matrix.
    Use case: Used for measuring vector magnitudes or the "size" of matrices.
    Example:

    norm_value = np.linalg.norm(x)

6. np.linalg.matrix_rank(A): Rank of a Matrix

    Purpose: Computes the rank of a matrix (the dimension of the vector space spanned by its rows or columns).
    Use case: Helps in determining the linear independence of rows or columns and is used in solving linear systems.
    Example:

    rank = np.linalg.matrix_rank(A)

7. np.linalg.cholesky(A): Cholesky Decomposition

    Purpose: Computes the Cholesky decomposition of a positive-definite matrix.
    Use case: Used in optimization and solving systems of equations.
    Example:

    L = np.linalg.cholesky(A)

8. np.linalg.svd(A): Singular Value Decomposition

    Purpose: Computes the Singular Value Decomposition (SVD) of a matrix.
    Use case: SVD is widely used in signal processing, data compression, and dimensionality reduction (e.g., PCA).
    Example:

    U, S, Vt = np.linalg.svd(A)

9. np.linalg.lstsq(A, B): Least Squares Solution

    Purpose: Solves the least squares problem for over-determined systems.
    Use case: Used when you have more equations than unknowns (i.e., an over-determined system).
    Example:

X, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)